version: "2"

services:
  api:
    build: .
    image: product-mgmt:latest
    container_name: product-mgmt-app
    ports:
      - "9090:9090"
    networks:
      - backend
      - frontend
    environment:
      - "DATABASE_HOST=product-mgmt-db"
      - "DATABASE_PORT=5432"
      - "DATABASE_NAME=product-mgmt"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=1023040"
      - "CACHE_HOST=product-mgmt-cache"
      - "CACHE_PORT=6379"
      - "CACHE_PASSWORD=123456"      
      - "ENVIRONMENT=prod"         
    restart: always

  db:
    image: postgres
    container_name: product-mgmt-db
    networks:
      - backend
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=1023040"
      - "POSTGRES_DB=product-mgmt"
    volumes:
      - /home/leandro/Projetos/docker/volume/product-mgmt/postgres:/var/lib/postgresql/data
    ports:
      - "5432"
    restart: always

  redis:
    image: redis:latest
    container_name: product-mgmt-cache
    networks:
      - backend    
    ports:
      - "6379:6379"
    environment:
      - "REDIS_PASSWORD=123456"
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]
    volumes:
      - /home/leandro/Projetos/docker/volume/product-mgmt/redis:/data
    restart: unless-stopped

networks:
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    internal: true