server:
  port: 9090
spring:
    cache:
      type: redis
    data:
      redis:
        host: ${CACHE_HOST}
        port: ${CACHE_PORT}
        password: ${CACHE_PASSWORD}
    datasource:
        url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}

    jpa:
        show-sql: false
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
    flyway: 
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
    