apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}      
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}-container
        image: lgomesb/{{ .Release.Name }}:latest
        env:
        {{- range $env := .Values.env }}
        - name: {{ $env.name }}          
          {{- with $env.valueFrom }}
          valueFrom: 
            secretKeyRef:
              name: {{ .secretKeyRef.name }}
              key: {{ .secretKeyRef.key }}
          {{- else }}
          value: {{ $env.value }}
          {{- end }}
        {{- end }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu | default "400m" }}
            memory: {{ .Values.resources.requests.cpu | default "0.5G" }}
          limits:
            cpu: {{ .Values.resources.requests.cpu | default "2" }}
            memory: {{ .Values.resources.requests.cpu | default "1.0G" }}
        ports:
        - containerPort: {{ .Values.port | default 9090 }}
        livenessProbe:
          httpGet:
            path: {{ .Values.context_path | default .Release.Name }}/actuator/health/liveness
            port: {{ .Values.port | default 9090 }}
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 10
  replicas: 2
