apiVersion: v1
kind: Service
metadata:
  name: product-mgmt-svc
  namespace: product-mgmt
spec:
  selector:
    app: product-mgmt-app
  ports:
  - port: 9090
    targetPort: 9090
    protocol:  TCP
  externalTrafficPolicy: Local  
  type: LoadBalancer